language: python
os:
  - linux
python:
  - 3.8
install:
  - python -m pip install -U pip

before_script:
  - pip install -I numpy==1.20.3
  - pip install pytest-cov
script:
  - pytest -v --cov=./ --cov-report=xml

after_success:
    - bash < (curl -s https://codecov.io/bash)